- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 201
  key: litecoin
  currency: ltc
  fixed: 8
  fee: 0.0001
  inuse: true
  type: WithdrawChannelLitecoin
- id: 203
  key: dash
  currency: dash
  fixed: 8
  fee: 0.0001
  inuse: true
  type: WithdrawChannelDash
- id: 400
  key: bank
  currency: usd
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelBank
